#!/usr/bin/env python
from __future__ import print_function
import nbgit


#########################################################################
#
# NBGIT: 
#   -   This file is automatically created/append to .git/hooks/pre-commit 
#       upon nbgit.install().
#   -   Upon commiting:
#       - all notebooks will be converted to .nbpy.py files
#       - if AUTO_ADD_NBPY==True:
#           .nbpy.py files are added to the repo
#   
#########################################################################


#
# CONVERT
#
print('nbgit: looking for notebooks...')
nbgit.convert_all()


