#!/usr/bin/env python
from __future__ import print_function
import nb_git
import nb_git.config as con


#########################################################################
#
# NBGIT: 
#   -   This file is automatically created/append to .git/hooks/pre-commit 
#       upon nb_git.install().
#   -   Upon commiting:
#       - all notebooks will be converted to .nbpy.py files
#       - if AUTO_ADD_NBPY==True:
#           .nbpy.py files are added to the repo
#   
#########################################################################


#
# CONVERT
#
if con.fig('AUTO_TRACK_ALL_NOTEBOOKS'):
    nb_git.add('.')


if con.fig('UPDATE_ON_COMMIT'):
    nb_git.update()


