#!/usr/bin/env python
from __future__ import print_function
import nb_git


#########################################################################
#
# NBGIT: 
#   -   This file is automatically created/append to .git/hooks/pre-commit 
#       upon nb_git.install().
#   -   Upon commiting:
#       - all notebooks will be converted to .nbpy.py files
#       - if AUTO_ADD_NBPY==True:
#           .nbpy.py files are added to the repo
#   
#########################################################################


#
# CONVERT
#
print('nb_git: looking for notebooks...')
nb_git.convert_all()


